services:
  - type: web
    name: chrispar-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT app:create_app()"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: chrispar-db
          property: connectionString

databases:
  - name: chrispar-db
    databaseName: chrispar
    user: chrispar_user