version: '3.8'

services:
  file-server:
    build: .
    container_name: file_server_container
    restart: always
    ports:
      - "5000:8000"
      # Windows (5000) -> Contenedor (8000)
    volumes:
      - ./storage:/app/storage
      #storage en windows -> storage en contenedor